USE INFO330_Proj_4

-- OS
INSERT INTO tblVERSION(VersionName) VALUES ('Catalina')
INSERT INTO tblVERSION(VersionName) VALUES ('81.0.4044.127')
INSERT INTO tblVERSION(VersionName) VALUES ('10 Home')
INSERT INTO tblVERSION(VersionName) VALUES ('10 Pro')

INSERT INTO tblSTYLUS_SUPPORT(StylusSupport) VALUES ('TRUE')
INSERT INTO tblSTYLUS_SUPPORT(StylusSupport) VALUES ('FALSE')

-- Display
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (13.3)
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (12.3)
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (15.6)
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (16.0)
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (13.5)
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (17.3)
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (14.0)
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (15.2)
INSERT INTO tblDISPLAY_SIZE(DisplaySize) VALUES (15.4)

INSERT INTO tblRESOLUTION(Resolution) VALUES ('2500 x 1600')
INSERT INTO tblRESOLUTION(Resolution) VALUES ('1920 x 1080')
INSERT INTO tblRESOLUTION(Resolution) VALUES ('2736 x 1824')
INSERT INTO tblRESOLUTION(Resolution) VALUES ('3072 x 1920')
INSERT INTO tblRESOLUTION(Resolution) VALUES ('2256 x 1504')
INSERT INTO tblRESOLUTION(Resolution) VALUES ('3840 x 2160')
INSERT INTO tblRESOLUTION(Resolution) VALUES ('2880 x 1800')

-- CPU
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (3.2)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (2.6)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (3.6)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (4.5)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (3.9)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (1.6)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (2.4)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (4.7)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (2.3)
INSERT INTO tblCLOCK_SPEED(ClockSpeed) VALUES (4.1)

INSERT INTO tblNUM_CORES(NumCores) VALUES (2)
INSERT INTO tblNUM_CORES(NumCores) VALUES (4)
INSERT INTO tblNUM_CORES(NumCores) VALUES (6)
INSERT INTO tblNUM_CORES(NumCores) VALUES (8)

-- Graphics
INSERT INTO tblRELEASE_YEAR(ReleaseYear) VALUES ('2015')
INSERT INTO tblRELEASE_YEAR(ReleaseYear) VALUES ('2016')
INSERT INTO tblRELEASE_YEAR(ReleaseYear) VALUES ('2017')
INSERT INTO tblRELEASE_YEAR(ReleaseYear) VALUES ('2018')
INSERT INTO tblRELEASE_YEAR(ReleaseYear) VALUES ('2019')
INSERT INTO tblRELEASE_YEAR(ReleaseYear) VALUES ('2020')

-- Security
INSERT INTO tblSECURITY_TYPE(SecurityType) VALUES ('Fingerprint')
INSERT INTO tblSECURITY_TYPE(SecurityType) VALUES ('Password')
INSERT INTO tblSECURITY_TYPE(SecurityType) VALUES ('Face sign-in')

-- Webcam
INSERT INTO tblPROGRESSIVE_SCAN(ProgressiveScan) VALUES (720)
INSERT INTO tblPROGRESSIVE_SCAN(ProgressiveScan) VALUES (1080)

-- Audio
INSERT INTO tblNUM_SPEAKERS(NumSpeakers) VALUES (1)
INSERT INTO tblNUM_SPEAKERS(NumSpeakers) VALUES (2)
INSERT INTO tblNUM_SPEAKERS(NumSpeakers) VALUES (3)
INSERT INTO tblNUM_SPEAKERS(NumSpeakers) VALUES (6)

-- Storage
INSERT INTO tblSTORAGE_SIZE(Size) VALUES (64)
INSERT INTO tblSTORAGE_SIZE(Size) VALUES (128)
INSERT INTO tblSTORAGE_SIZE(Size) VALUES (256)
INSERT INTO tblSTORAGE_SIZE(Size) VALUES (512)
INSERT INTO tblSTORAGE_SIZE(Size) VALUES (1028)
INSERT INTO tblSTORAGE_SIZE(Size) VALUES (3000)
INSERT INTO tblSTORAGE_SIZE(Size) VALUES (4000)