USE INFO330_Proj_4

CREATE TABLE tblREVIEW (
  ReviewID INT IDENTITY (1, 1) PRIMARY KEY,
  RatingID INT,
  CommentID INT,
  ProductOrderID INT,
  CONSTRAINT FK_RatingID FOREIGN KEY (RatingID)
  REFERENCES tblRATING(RatingID),
  CONSTRAINT FK_CommentID FOREIGN KEY (CommentID)
  REFERENCES tblCOMMENT(CommentID),
)

ALTER TABLE tblREVIEW
ADD ProductOrderID INT

ALTER TABLE tblREVIEW
ADD CONSTRAINT FK_ProductOrderID FOREIGN KEY (ProductOrderID)
REFERENCES tblPRODUCT_ORDER(ProductOrderID)

GO 
CREATE TABLE tblCOMMENT (
	CommentID INT IDENTITY (1, 1) PRIMARY KEY,
	CommentBody varchar(500),
  ReviewID INT
)

ALTER TABLE tblCOMMENT
ADD CONSTRAINT FK_ReviewID FOREIGN KEY (ReviewID)
REFERENCES tblREVIEW (ReviewID)

GO 
CREATE TABLE tblRATING (
	RatingID INT IDENTITY (1, 1) PRIMARY KEY,
	RatingValue INT
)

ALTER TABLE tblRATING
ADD RatingName varchar(50)